### ISSUE TITLE
Using with stable-baselines3

### ISSUE THREAD

**Issue by aseembits93** [automl/CARL#103]
Hi, 

Thank you for this software, it's really useful for my research. I'm currently running some baseline algorithms with stable-baselines3 and somehow I have trouble instantiating the replay buffer. it demands the action space to be of the type 'gymnasium.spaces.box.Box' although the type of the carl environment is 'gym.spaces.box.Box'. let me know how I could fix it? Thanks!

**Comment by benjamc** [comment]
Hi,
great to hear!
Which environment did you try to instantiate?
Actually we moved everything to `gymnasium`, but maybe we missed a piece.
Other than that it is probably possible to convert `gym` action spaces to `gymnasium` action spaces.

**Comment by sai-prasanna** [comment]
@benjamc I found the issue, https://github.com/automl/CARL/issues/109 I can submit a fix if we decide how to go about it.

**Comment by TheEimer** [comment]
#109 is fixed now on dev, so this shouldn't be an issue in DMControl anymore. We also did gym registration for Box2D, the gymnasium and dm envs now, so this should guarantee everything is up to spec. 
Brax is not included here, since the spaces are different again - this is on our list though! Feel free to re-open if there was another environment you had an issue with.
