### ISSUE TITLE
Update to gymnasium

### ISSUE THREAD

**Issue by benjamc** [automl/CARL#74]

**Comment by elliottower** [comment]
Hi, just following up on this to see if there are any plans to migrate. This repository is currently listed in the gymnasium [third party environments](https://gymnasium.farama.org/environments/third_party_environments/) but we are cleaning the list up to only include maintained gymnasium-compatible repositories. No worries if not, just figured I would reach out and see the status of things.

**Comment by TheEimer** [comment]
We're currently working on it and the update should happen soon-ish. WE#ll comment here once the new version is out.

**Comment by elliottower** [comment]
> We're currently working on it and the update should happen soon-ish. WE#ll comment here once the new version is out.

Awesome, thanks for the update. Will add your project to our list of third party environments once it is done (https://gymnasium.farama.org/environments/third_party_environments/)

**Comment by TheEimer** [comment]
This took longer than we wanted, but the new release now switched to gymnasium @elliottower :D

**Comment by elliottower** [comment]
> This took longer than we wanted, but the new release now switched to gymnasium @elliottower :D

Great to hear, thanks for letting me know. Would you like to make a PR updating the [third party environments list](https://gymnasium.farama.org/environments/third_party_environments/)? Otherwise we can do it on our end, but if you want to change the description or anything like that feel free. We do the environments in alphabetical order on that page.

**Comment by TheEimer** [comment]
I created a PR here: https://github.com/Farama-Foundation/Gymnasium/pull/668
